FusionCharts.ready(function () {
  new FusionCharts({
    type: "sunburst",
    renderAt: "container-current-1",
    width: "580",
    height: "580",
    dataFormat: "json",
    dataSource: {
      chart: {
        theme: "fusion",
        caption: "Module 1 Current Learning Goals",
        subcaption: "Click on the segments to Drill-down",
        showPlotBorder: "1",
        animation: "1",
        paletteColors: "D7D8E7, 11F1FB, FAAE03, EF3752,",
        animationDuration: "2",
        centerAngle: "360",
        textOutline: "0",
      },
      data: [
        {
          id: "Learning Goals",
          parent: "",
          label: "M1 Goals",
          value: "",
        },
        {
          id: "Mastery",
          parent: "Learning Goals",
          label: "Mastery",
          value: "1",
        },
        {
          id: "Ruby-M",
          parent: "Mastery",
          label: "Ruby",
          value: "1",
        },
        {
          id: "Strings",
          parent: "Ruby-M",
          label: "String Manipulation",
          value: "1",
        },
        {
          id: "Nums",
          parent: "Ruby-M",
          label: "Difference between Ints & Floats",
          value: "1",
        },
        {
          id: "Lists",
          parent: "Ruby-M",
          label: "Difference between Arrays & Hashes",
          value: "1",
        },
        {
          id: "Symbols",
          parent: "Ruby-M",
          label: "Utilize Symbols",
          value: "1",
        },
        {
          id: "Iteration",
          parent: "Ruby-M",
          label: "Use enumberables",
          value: "1",
        },
        {
          id: "Flow",
          parent: "Ruby-M",
          label: "Flow Control",
          value: "1",
        },
        {
          id: "Booleans",
          parent: "Ruby-M",
          label: "Utilize booleans",
          value: "1",
        },
        {
          id: "Components",
          parent: "Ruby-M",
          label: "Utilize methods, arguments, return values",
          value: "1",
        },
        {
          id: "Design-M",
          parent: "Mastery",
          label: "Design",
          value: "1",
        },
        {
          id: "State & Behavior",
          parent: "Design-M",
          label: "State & Behavior",
          value: "1",
        },
        {
          id: "Breakdown",
          parent: "Design-M",
          label: "Processes for breaking down problems",
          value: "1",
        },
        {
          id: "TDD",
          parent: "Design-M",
          label: "Test Driven Development",
          value: "1",
        },
        {
          id: "SRP",
          parent: "Design-M",
          label: "SRP & DRY",
          value: "1",
        },
        {
          id: "Readablity",
          parent: "Design-M",
          label: "Code Readability",
          value: "1",
        },
        {
          id: "Testing-M",
          parent: "Mastery",
          label: "Testing",
          value: "1",
        },
        {
          id: "Identify",
          parent: "Testing-M",
          label: "Identify testability",
          value: "1",
        },
        {
          id: "Assertions",
          parent: "Testing-M",
          label: "Write good assertions",
          value: "1",
        },
        {
          id: "Translations",
          parent: "Testing-M",
          label: "Translate technical specifications into tests",
          value: "1",
        },
        {
          id: "TDD",
          parent: "Testing-M",
          label: "Write tests first",
          value: "1",
        },
        {
          id: "Debugging-M",
          parent: "Mastery",
          label: "Debugging",
          value: "1",
        },
        {
          id: "Diagnose",
          parent: "Debugging-M",
          label: "Diagnose & Fix bugs",
          value: "1",
        },
        {
          id: "Errors",
          parent: "Debugging-M",
          label: "Understand common ruby errors",
          value: "1",
        },
        {
          id: "Pry",
          parent: "Debugging-M",
          label: "Use Pry for breakpoints",
          value: "1",
        },
        {
          id: "Scope",
          parent: "Debugging-M",
          label: "Understand variable scopes",
          value: "1",
        },
        {
          id: "Git-M",
          parent: "Mastery",
          label: "Version Control",
          value: "1",
        },
        {
          id: "repos",
          parent: "Git-M",
          label: "Difference between local & remote repos",
          value: "1",
        },
        {
          id: "commands",
          parent: "Git-M",
          label: "Push, Pull, Commit, Branch",
          value: "1",
        },
        {
          id: "commits",
          parent: "Git-M",
          label: "Commit frequently",
          value: "1",
        },
        {
          id: "PRs",
          parent: "Git-M",
          label: "Submit & Merge PRs",
          value: "1",
        },
        {
          id: "communication",
          parent: "Git-M",
          label: "Use Git & GitHub for collaboration",
          value: "1",
        },
        {
          id: "Desktop-M",
          parent: "Mastery",
          label: "Command Line",
          value: "1",
        },
        {
          id: "navigation",
          parent: "Desktop-M",
          label: "Navigate machine to write & rub Ruby",
          value: "1",
        },
        {
          id: "explaination",
          parent: "Desktop-M",
          label: "Explain cli & text editor interaction",
          value: "1",
        },
        {
          id: "Functional",
          parent: "Learning Goals",
          label: "Functional",
          value: "1",
        },
        {
          id: "Ruby-F",
          parent: "Functional",
          label: "Ruby",
          value: "1",
        },
        {
          id: "inheritance",
          parent: "Ruby-F",
          label: "Implement Inheritance",
          value: "1",
        },
        {
          id: "mixins",
          parent: "Ruby-F",
          label: "Implement Mixins",
          value: "1",
        },
        {
          id: "files",
          parent: "Ruby-F",
          label: "Import & Export data to files",
          value: "1",
        },
        {
          id: "class methods",
          parent: "Ruby-F",
          label: "Write class methods",
          value: "1",
        },
        {
          id: "cvi",
          parent: "Ruby-f",
          label: "Difference between class & instance methods",
          value: "1",
        },
        {
          id: "Design-F",
          parent: "Functional",
          label: "Design",
          value: "1",
        },
        {
          id: "mvi",
          parent: "Design-F",
          label: "Identify uses for modules vs. inheritance",
          value: "1",
        },
        {
          id: "vars",
          parent: "Design-F",
          label: "Limit instance vars",
          value: "1",
        },
        {
          id: "SRP",
          parent: "Design-F",
          label: "Write code that meets SRP & DRY",
          value: "1",
        },
        {
          id: "Testing-F",
          parent: "Functional",
          label: "Testing",
          value: "1",
        },
        {
          id: "documentation",
          parent: "Testing-F",
          label: "Write tests to read like documentation",
          value: "1",
        },
        {
          id: "edge",
          parent: "Testing-F",
          label: "Implement Edge Case testing",
          value: "1",
        },
        {
          id: "types",
          parent: "Testing-F",
          label: "Write unit & Integration tests",
          value: "1",
        },
        {
          id: "stub",
          parent: "Testing-F",
          label: "Implement stub in integration tests",
          value: "1",
        },
        {
          id: "Debugging-F",
          parent: "Functional",
          label: "Debugging",
          value: "1",
        },
        {
          id: "docs",
          parent: "Debugging-F",
          label: "Utilize docs/recources for debugging",
          value: "1",
        },
        {
          id: "Git-F",
          parent: "Functional",
          label: "Version Control",
          value: "1",
        },
        {
          id: "comments",
          parent: "Git-F",
          label: "Comment on code in GitHub",
          value: "1",
        },
        {
          id: "resolution",
          parent: "Git-F",
          label: "Resolve Merge Conflicts",
          value: "1",
        },
        {
          id: "Desktop-F",
          parent: "Functional",
          label: "Desktop",
          value: "1",
        },
        {
          id: "shortcuts",
          parent: "Desktop-F",
          label: "Utilize keyboard shortcuts",
          value: "1",
        },
        {
          id: "Familiar",
          parent: "Learning Goals",
          label: "Familiar",
          value: "1",
        },
        {
          id: "Ruby-Fam",
          parent: "Familiar",
          label: "Ruby",
          value: "1",
        },
        {
          id: "scopes",
          parent: "Ruby-Fam",
          label: "Explain local vs instance var scope",
          value: "1",
        },
        {
          id: "memory",
          parent: "Ruby-Fam",
          label: "Explain memory allocation in Ruby",
          value: "1",
        },
        {
          id: "call stack",
          parent: "Ruby-Fam",
          label: "Explain call stack",
          value: "1",
        },
        {
          id: "Testing-Fam",
          parent: "Familiar",
          label: "Testing",
          value: "1",
        },
        {
          id: "mocks/stubs",
          parent: "Testing-Fam",
          label: "Explain mocks and stubs",
          value: "1",
        },
      ],
    },
  }).render();
});
