FusionCharts.ready(function () {
  new FusionCharts({
    type: "sunburst",
    renderAt: "container-3",
    width: "900",
    height: "650",
    dataFormat: "json",
    dataSource: {
      chart: {
        theme: "fusion",
        caption: "Module 3 Learning Goals from Curriculum Analysis",
        subcaption: "Click on the segments to Drill-down",
        showPlotBorder: "1",
        animation: "1",
        paletteColors: "D7D8E7, 11F1FB, FAAE03, EF3752,",
        animationDuration: "2",
        centerAngle: "360",
        textOutline: "0",
      },
      data: [
        {
          id: "Learning Goals",
          parent: "",
          label: "M3 Goals",
          value: "1",
        },
        {
          id: "Mastery",
          parent: "Learning Goals",
          label: "Mastery",
          value: "1",
        },
        {
          id: "OOP/Ruby-M",
          parent: "Mastery",
          label: "OOP/Ruby",
          value: "1",
        },
        {
          id: "HTTP",
          parent: "OOP/Ruby-M",
          label: "HTTP Libraries",
          value: "1",
        },
        {
          id: "Conventions",
          parent: "OOP/Ruby-M",
          label: "Ruby Conventions",
          value: "1",
        },
        {
          id: "SRP",
          parent: "OOP/Ruby-M",
          label: "Single Responsibility Principle",
          value: "1",
        },
        {
          id: "Demeter",
          parent: "OOP/Ruby-M",
          label: "Law of Demeter",
          value: "1",
        },
        {
          id: "APIs-M",
          parent: "Mastery",
          label: "APIs",
          value: "1",
        },
        {
          id: "Open",
          parent: "APIs-M",
          label: "Consume APIs with and without Auth",
          value: "1",
        },
        {
          id: "OAuth Access",
          parent: "APIs-M",
          label: "OAuth",
          value: "1",
        },
        {
          id: "OmniAuth",
          parent: "APIs-M",
          label: "OmniAuth",
          value: "1",
        },
        {
          id: "Services",
          parent: "APIs-M",
          label: "Organize code with Services",
          value: "1",
        },
        {
          id: "Exposing",
          parent: "APIs-M",
          label: "Create APIs in Rails",
          value: "1",
        },
        {
          id: "Serializers",
          parent: "APIs-M",
          label: "Use Serializers",
          value: "1",
        },
        {
          id: "Web-M",
          parent: "Mastery",
          label: "Web",
          value: "1",
        },
        {
          id: "HTTP Request/Response",
          parent: "Web-M",
          label: "HTTP Request/Response",
          value: "1",
        },
        {
          id: "REST",
          parent: "Web-M",
          label: "Understanding ReST Architecture",
          value: "1",
        },
        {
          id: "Routes",
          parent: "Web-M",
          label: "Nested & Namespaced Routes",
          value: "1",
        },
        {
          id: "HTML/CSS",
          parent: "Web-M",
          label: "HTML & CSS",
          value: "1",
        },
        {
          id: "Rails",
          parent: "Web-M",
          label: "Rails Framework",
          value: "1",
        },
        {
          id: "Testing-M",
          parent: "Mastery",
          label: "Testing",
          value: "1",
        },
        {
          id: "Capybara",
          parent: "Testing-M",
          label: "Capybara",
          value: "1",
        },
        {
          id: "Mocks & Stubs",
          parent: "Testing-M",
          label: "Mocks & Stubs",
          value: "1",
        },
        {
          id: "RSpec",
          parent: "Testing-M",
          label: "RSpec",
          value: "1",
        },
        {
          id: "Top Down Testing",
          parent: "Testing-M",
          label: "Top Down Testing",
          value: "1",
        },
        {
          id: "Bottom Up Testing",
          parent: "Testing-M",
          label: "Bottom Up Testing",
          value: "1",
        },
        {
          id: "Database-M",
          parent: "Mastery",
          label: "Database",
          value: "1",
        },
        {
          id: "Migrations",
          parent: "Database-M",
          label: "Migrations",
          value: "1",
        },
        {
          id: "Relationships",
          parent: "Database-M",
          label: "One-to-Many & Many-to-Many",
          value: "1",
        },
        {
          id: "Foreign Keys",
          parent: "Database-M",
          label: "Foreign & Primary Keys",
          value: "1",
        },
        {
          id: "Normalization",
          parent: "Database-M",
          label: "Normalization",
          value: "1",
        },
        {
          id: "Join",
          parent: "Database-M",
          label: "Join Query",
          value: "1",
        },
        {
          id: "Search",
          parent: "Database-M",
          label: "Where & Find Queries",
          value: "1",
        },
        {
          id: "Aggregating",
          parent: "Database-M",
          label: "Aggregating Query",
          value: "1",
        },
        {
          id: "Group",
          parent: "Database-M",
          label: "Group Query",
          value: "1",
        },
        {
          id: "Select",
          parent: "Database-M",
          label: "Select Query",
          value: "1",
        },
        {
          id: "SQL",
          parent: "Database-M",
          label: "SQL",
          value: "1",
        },
        {
          id: "AR Associations",
          parent: "Database-M",
          label: "Active Record Associations",
          value: "1",
        },
        {
          id: "Ops-M",
          parent: "Mastery",
          label: "Ops",
          value: "1",
        },
        {
          id: "Heroku",
          parent: "Ops-M",
          label: "Deploy to Heroku",
          value: "1",
        },
        {
          id: "Functional",
          parent: "Learning Goals",
          label: "Functional",
          value: "1",
        },
        {
          id: "OOP/Ruby-Fun",
          parent: "Functional",
          label: "OOP/Ruby",
          value: "1",
        },
        {
          id: "Mixins",
          parent: "OOP/Ruby-Fun",
          label: "Mixins",
          value: "1",
        },
        {
          id: "CSVs",
          parent: "OOP/Ruby-Fun",
          label: "Reading CSVs",
          value: "1",
        },
        {
          id: "Error Handling",
          parent: "OOP/Ruby-Fun",
          label: "Error Handling",
          value: "1",
        },
        {
          id: "Design Patterns",
          parent: "OOP/Ruby-Fun",
          label: "Design Patterns/SOLID/4 Pillars",
          value: "1",
        },
        {
          id: "Refactoring",
          parent: "OOP/Ruby-Fun",
          label: "Code Smells & Refactoring",
          value: "1",
        },
        {
          id: "APIs-Fun",
          parent: "Functional",
          label: "APIs",
          value: "1",
        },
        {
          id: "Architecture",
          parent: "APIs-Fun",
          label: "Architecture Patterns SOA/Monolith",
          value: "1",
        },
        {
          id: "Web-Fun",
          parent: "Functional",
          label: "Web",
          value: "1",
        },
        {
          id: "Cookies/Sessions",
          parent: "Web-Fun",
          label: "Cookies & Sessions",
          value: "1",
        },
        {
          id: "Sinatra",
          parent: "Web-Fun",
          label: "Sinatra Framework",
          value: "1",
        },
        {
          id: "Git-Fun",
          parent: "Functional",
          label: "Git",
          value: "1",
        },
        {
          id: "Cherry Picking",
          parent: "Git-Fun",
          label: "Cherry Picking",
          value: "1",
        },
        {
          id: "Amend",
          parent: "Git-Fun",
          label: "Amend",
          value: "1",
        },
        {
          id: "Optimization-Fun",
          parent: "Functional",
          label: "Optimization",
          value: "1",
        },
        {
          id: "Background Workers",
          parent: "Optimization-Fun",
          label: "Background Workers",
          value: "1",
        },
        {
          id: "Memoization",
          parent: "Optimization-Fun",
          label: "Memoization",
          value: "1",
        },
        {
          id: "Big O",
          parent: "Optimization-Fun",
          label: "Big O",
          value: "1",
        },
        {
          id: "Includes",
          parent: "Optimization-Fun",
          label: "Includes Query",
          value: "1",
        },
        {
          id: "Preload/Eager Load",
          parent: "Optimization-Fun",
          label: "Preload & Eager Load",
          value: "1",
        },
        {
          id: "Database-Fun",
          parent: "Functional",
          label: "Datbase",
          value: "1",
        },
        {
          id: "Scopes",
          parent: "Database-Fun",
          label: "Active Record Scopes",
          value: "1",
        },
        {
          id: "Ops-Fun",
          parent: "Functional",
          label: "Ops",
          value: "1",
        },
        {
          id: "CI",
          parent: "Ops-Fun",
          label: "Continuous Integration",
          value: "1",
        },
        {
          id: "Public",
          parent: "Ops-Fun",
          label: "Understanding Public Folder in Rails",
          value: "1",
        },
        {
          id: "CS-Fun",
          parent: "Functional",
          label: "CS Topics",
          value: "1",
        },
        {
          id: "Queue",
          parent: "CS-Fun",
          label: "Queues",
          value: "1",
        },
        {
          id: "Security-Fun",
          parent: "Functional",
          label: "Security",
          value: "1",
        },
        {
          id: "Exposing Data",
          parent: "Security-Fun",
          label: "Only exposing necessary data",
          value: "1",
        },
        {
          id: "Familiar",
          parent: "Learning Goals",
          label: "Familiar",
          value: "1",
        },
        {
          id: "Web-Fam",
          parent: "Familiar",
          label: "Web",
          value: "1",
        },
        {
          id: "JS",
          parent: "Web-Fam",
          label: "Front End JavaScript",
          value: "1",
        },
        {
          id: "Command Line",
          parent: "Familiar",
          label: "Command Line",
          value: "1",
        },
        {
          id: "pipe",
          parent: "Command Line",
          label: "pipe",
          value: "1",
        },
        {
          id: "grep",
          parent: "Command Line",
          label: "grep",
          value: "1",
        },
        {
          id: "less",
          parent: "Command Line",
          label: "less",
          value: "1",
        },
        {
          id: "cat",
          parent: "Command Line",
          label: "cat",
          value: "1",
        },
        {
          id: "Optimization-Fam",
          parent: "Familiar",
          label: "Optimization",
          value: "1",
        },
        {
          id: "Caching",
          parent: "Optimization-Fam",
          label: "Caching",
          value: "1",
        },
        {
          id: "Database-Fam",
          parent: "Familiar",
          label: "Database",
          value: "1",
        },
        {
          id: "Callbacks",
          parent: "Database-Fam",
          label: "Callbacks",
          value: "1",
        },
        {
          id: "Security-Fam",
          parent: "Familiary",
          label: "Security",
          value: "1",
        },
        {
          id: "CSRF",
          parent: "Security-Fam",
          label: "Cross Site Request Forgery & CORS",
          value: "1",
        },
        {
          id: "SQL Injection",
          parent: "Security-Fam",
          label: "SQL Injection",
          value: "1",
        },
        {
          id: "Encrypting",
          parent: "Security-Fam",
          label: "Encrypt & Hash sensitive data",
          value: "1",
        },
        {
          id: "Click",
          parent: "Security-Fam",
          label: "Click-jacking",
          value: "1",
        },
        {
          id: "XSS",
          parent: "Security-Fam",
          label: "Cross-Site Scripting",
          value: "1",
        },
      ],
    },
  }).render();
});
