FusionCharts.ready(function () {
  var topStores = new FusionCharts({
    type: "sunburst",
    renderAt: "container-1",
    width: "900",
    height: "650",
    dataFormat: "json",
    dataSource: {
      chart: {
        theme: "fusion",
        caption: "Module 1 Learning Goals from Curriculum Analysis",
        subcaption: "Click on the segments to Drill-down",
        showPlotBorder: "1",
        animation: "1",
        paletteColors: "D7D8E7, 11F1FB, FAAE03, EF3752,",
        animationDuration: "2",
        centerAngle: "360",
        textOutline: "0",
      },
      data: [
        {
          id: "Learning Goals",
          parent: "",
          label: "M1 Goals",
          value: "",
        },
        {
          id: "Mastery",
          parent: "Learning Goals",
          label: "Mastery",
          value: "1",
        },
        {
          id: "OOP/Ruby-M",
          parent: "Mastery",
          label: "OOP/Ruby",
          value: "1",
        },
        {
          id: "Data Types",
          parent: "OOP/Ruby-M",
          label: "Data Types",
          value: "1",
        },
        {
          id: "Iteration",
          parent: "OOP/Ruby-M",
          label: "Iteration",
          value: "1",
        },
        {
          id: "Classes",
          parent: "OOP/Ruby-M",
          label: "Classes",
          value: "1",
        },
        {
          id: "SRP",
          parent: "OOP/Ruby-M",
          label: "SRP",
          value: "1",
        },
        {
          id: "Methods",
          parent: "OOP/Ruby-M",
          label: "Methods",
          value: "1",
        },
        {
          id: "Control Flow",
          parent: "OOP/Ruby-M",
          label: "Control Flow",
          value: "1",
        },
        {
          id: "String Manipulation",
          parent: "OOP/Ruby-M",
          label: "String Manipulation",
          value: "1",
        },
        {
          id: "Git-M",
          parent: "Mastery",
          label: "Version Control",
          value: "1",
        },
        {
          id: "Init",
          parent: "Git-M",
          label: "Init",
          value: "1",
        },
        {
          id: "Add",
          parent: "Git-M",
          label: "Add",
          value: "1",
        },
        {
          id: "Commit",
          parent: "Git-M",
          label: "Commit",
          value: "1",
        },
        {
          id: "Push",
          parent: "Git-M",
          label: "Push",
          value: "1",
        },
        {
          id: "Pull",
          parent: "Git-M",
          label: "Pull",
          value: "1",
        },
        {
          id: "Status",
          parent: "Git-M",
          label: "Status",
          value: "1",
        },
        {
          id: "Fetch",
          parent: "Git-M",
          label: "Fetch",
          value: "1",
        },
        {
          id: "Merge",
          parent: "Git-M",
          label: "Merge",
          value: "1",
        },
        {
          id: "Branch",
          parent: "Git-M",
          label: "Branch",
          value: "1",
        },
        {
          id: "Checkout",
          parent: "Git-M",
          label: "Checkout",
          value: "1",
        },
        {
          id: "Command Line-M",
          parent: "Mastery",
          label: "Command Line",
          value: "1",
        },
        {
          id: "ls",
          parent: "Command Line-M",
          label: "ls",
          value: "1",
        },
        {
          id: "cd",
          parent: "Command Line-M",
          label: "cd",
          value: "1",
        },
        {
          id: "mkdir",
          parent: "Command-Line-M",
          label: "mkdir",
          value: "1",
        },
        {
          id: "rm",
          parent: "Command Line-M",
          label: "rm",
          value: "1",
        },
        {
          id: "Testing-M",
          parent: "Mastery",
          label: "Testing",
          value: "1",
        },
        {
          id: "RSpec",
          parent: "Testing-M",
          label: "RSpec",
          value: "1",
        },
        {
          id: "TDD/Red Green Refactor",
          parent: "Testing-M",
          label: "TDD/Red Green Refactor",
          value: "1",
        },
        {
          id: "Functional",
          parent: "Learning Goals",
          label: "Functional",
          value: "1",
        },
        {
          id: "OOP/Ruby-Fun",
          parent: "Functional",
          label: "OOP/Ruby",
          value: "1",
        },
        {
          id: "File I/O",
          parent: "OOP/Ruby-Fun",
          label: "File I/O",
          value: "1",
        },
        {
          id: "Reading CSVs",
          parent: "OOP/Ruby-Fun",
          label: "Reading CSVs",
          value: "1",
        },
        {
          id: "Inheritance",
          parent: "OOP/Ruby-Fun",
          label: "Implemention of Inheritance",
          value: "1",
        },
        {
          id: "Testing-Fun",
          parent: "Functional",
          label: "Testing",
          value: "1",
        },
        {
          id: "Mocking/Stubbing",
          parent: "Testing-Fun",
          label: "Mocking/Stubbing",
          value: "1",
        },
        {
          id: "Security-Fun",
          parent: "Functional",
          label: "Security",
          value: "1",
        },
        {
          id: "Data",
          parent: "Security-Fun",
          label: "Only Expose Necessary Data",
          value: "1",
        },
        {
          id: "Familiar",
          parent: "Learning Goals",
          label: "Familiar",
          value: "1",
        },
        {
          id: "OOP/Ruby-Fam",
          parent: "Familiar",
          label: "OOP/Ruby",
          value: "1",
        },
        {
          id: "Mixins",
          parent: "OOP/Ruby-Fam",
          label: "Mixins",
          value: "1",
        },
        {
          id: "Namespacing",
          parent: "OOP/Ruby-Fam",
          label: "Namespacing",
          value: "1",
        },
        {
          id: "cmd-line",
          parent: "OOP/Ruby-Fam",
          label: "Command Line Arguments",
          value: "1",
        },
        {
          id: "REPL",
          parent: "OOP/Ruby-Fam",
          label: "Create a REPL",
          value: "1",
        },
        {
          id: "Design Patterns",
          parent: "OOP/Ruby-Fam",
          label: "4 Pillars/SOLID",
          value: "1",
        },
        {
          id: "Refactoring",
          parent: "OOP/Ruby-Fam",
          label: "Code Smells/Refactoring Patterns",
          value: "1",
        },
        {
          id: "Web",
          parent: "Familiar",
          label: "Web",
          value: "1",
        },
        {
          id: "HTTP Verbs",
          parent: "Web",
          label: "HTTP Verbs",
          value: "1",
        },
        {
          id: "Req/Resp",
          parent: "Web",
          label: "HTTP Request-Response",
          value: "1",
        },
        {
          id: "HTML",
          parent: "Web",
          label: "HTML",
          value: "1",
        },
        {
          id: "CSS",
          parent: "Web",
          label: "CSS",
          value: "1",
        },
        {
          id: "Git-Fam",
          parent: "Familar",
          label: "Version Control",
          value: "1",
        },
        {
          id: "stash",
          parent: "Git-Fam",
          label: "stash",
          value: "1",
        },
        {
          id: "log",
          parent: "Git-Fam",
          label: "log/reflog",
          value: "1",
        },
        {
          id: "reset",
          parent: "Git-Fam",
          label: "reset",
          value: "1",
        },
        {
          id: "Command Line-Fam",
          parent: "Familiar",
          label: "Command Line",
          value: "1",
        },
        {
          id: "pwd",
          parent: "Command Line-Fam",
          label: "pwd",
          value: "1",
        },
        {
          id: "touch",
          parent: "Command Line-Fam",
          label: "touch",
          value: "1",
        },
        {
          id: "cp",
          parent: "Command Line-Fam",
          label: "cp",
          value: "1",
        },
        {
          id: "mv",
          parent: "Command Line-Fam",
          label: "mv",
          value: "1",
        },
        {
          id: "Optimization",
          parent: "Familiar",
          label: "Optimization",
          value: "1",
        },
        {
          id: "Memoization",
          parent: "Optimization",
          label: "Memoization",
          value: "1",
        },
        {
          id: "Big O",
          parent: "Optimization",
          label: "Big O",
          value: "1",
        },
        {
          id: "Database",
          parent: "Familiar",
          label: "Database",
          value: "1",
        },
        {
          id: "ORM",
          parent: "Database",
          label: "ORM",
          value: "1",
        },
        {
          id: "One-to-Many",
          parent: "Database",
          label: "One-to-Many",
          value: "1",
        },
        {
          id: "Many-to-Many",
          parent: "Database",
          label: "Many-to-Many",
          value: "1",
        },
        {
          id: "CS Topics",
          parent: "Familiar",
          label: "CS Topics",
          value: "1",
        },
        {
          id: "Linked List",
          parent: "CS Topics",
          label: "Linked List",
          value: "1",
        },
        {
          id: "Binary Tree",
          parent: "CS Topic",
          label: "Binary Tree",
          value: "1",
        },
        {
          id: "Stack",
          parent: "CS Topic",
          label: "Stack",
          value: "1",
        },
        {
          id: "Queue",
          parent: "CS Topic",
          label: "Queue",
          value: "1",
        },
        {
          id: "Alogorithmic",
          parent: "Familiar",
          label: "Alogorithmic",
          value: "1",
        },
        {
          id: "Whiteboarding",
          parent: "Alogorithmic",
          label: "Whiteboarding",
          value: "1",
        },
        {
          id: "Recursion",
          parent: "Alogorithmic",
          label: "Recursion",
          value: "1",
        },
        {
          id: "Sorting",
          parent: "Alogorithmic",
          label: "Sorting",
          value: "1",
        },
        {
          id: "challenges",
          parent: "Alogorithmic",
          label: "Interview Code Challenges",
          value: "1",
        },
      ],
    },
  }).render();
});
