FusionCharts.ready(function () {
  var topStores = new FusionCharts({
    type: "sunburst",
    renderAt: "container-4",
    width: "900",
    height: "650",
    dataFormat: "json",
    dataSource: {
      chart: {
        theme: "fusion",
        caption: "Module 4 Learning Goals from Curriculum Analysis",
        subcaption: "Click on the segments to Drill-down",
        showPlotBorder: "1",
        animation: "1",
        paletteColors: "D7D8E7, 11F1FB, FAAE03, EF3752,",
        animationDuration: "2",
        centerAngle: "360",
        textOutline: "0",
      },
      data: [
        {
          id: "Learning Goals",
          parent: "",
          label: "M4 Goals",
          value: "1",
        },
        {
          id: "Mastery",
          parent: "Learning Goals",
          label: "Mastery",
          value: "1",
        },
        {
          id: "OOP-M",
          parent: "Mastery",
          label: "OOP",
          value: "1",
        },
        {
          id: "SRP",
          parent: "OOP-M",
          label: "SRP",
          value: "1",
        },
        {
          id: "Refactoring",
          parent: "OOP-M",
          label: "Code Smells & Refactoring",
          value: "1",
        },
        {
          id: "APIs-M",
          parent: "Mastery",
          label: "APIs",
          value: "1",
        },
        {
          id: "Open",
          parent: "APIs-M",
          label: "Consume Open APIs",
          value: "1",
        },
        {
          id: "Auth",
          parent: "APIs-M",
          label: "Consume APIs requiring auth",
          value: "1",
        },
        {
          id: "Services",
          parent: "APIs-M",
          label: "Utilizing Services for code organization",
          value: "1",
        },
        {
          id: "Web-M",
          parent: "Mastery",
          label: "Web",
          value: "1",
        },
        {
          id: "CORS/SQL",
          parent: "Web-M",
          label: "Understand CORS & SQL Injection",
          value: "1",
        },
        {
          id: "Testing-M",
          parent: "Mastery",
          label: "Testing",
          value: "1",
        },
        {
          id: "Mocks/Stubs",
          parent: "Testing-M",
          label: "Mocks & Stubs",
          value: "1",
        },
        {
          id: "RSpec",
          parent: "Testing-M",
          label: "RSpec",
          value: "1",
        },
        {
          id: "TDT",
          parent: "Testing-M",
          label: "Top Down Testing",
          value: "1",
        },
        {
          id: "BUT",
          parent: "Testing-M",
          label: "Bottom Up Testing",
          value: "1",
        },
        {
          id: "Database-M",
          parent: "Mastery",
          label: "Database-M",
          value: "1",
        },
        {
          id: "One-to-Many",
          parent: "Database-M",
          label: "One-to-Many",
          value: "1",
        },
        {
          id: "Many-to-Many",
          parent: "Database-M",
          label: "Many-to-Many",
          value: "1",
        },
        {
          id: "Foreign Keys",
          parent: "Database-M",
          label: "Foreign Keys",
          value: "1",
        },
        {
          id: "Primary Keys",
          parent: "Database-M",
          label: "Primary Keys",
          value: "1",
        },
        {
          id: "Normalization",
          parent: "Database-M",
          label: "Normalization",
          value: "1",
        },
        {
          id: "Ops-M",
          parent: "Mastery",
          label: "Ops",
          value: "1",
        },
        {
          id: "Heroku",
          parent: "Ops-M",
          label: "Heroku",
          value: "1",
        },
        {
          id: "CS-M",
          parent: "Mastery",
          label: "CS Topics",
          value: "1",
        },
        {
          id: "Whiteboarding",
          parent: "CS-M",
          label: "Whiteboarding",
          value: "1",
        },
        {
          id: "Code Challenges",
          parent: "CS-M",
          label: "Code Challenges",
          value: "1",
        },
        {
          id: "Security-M",
          parent: "Mastery",
          label: "Security",
          value: "1",
        },
        {
          id: "Exposure",
          parent: "Security-M",
          label: "Exposing only necessary data",
          value: "1",
        },
        {
          id: "Functional",
          parent: "Learning Goals",
          label: "Functional",
          value: "1",
        },
        {
          id: "OOP-Fun",
          parent: "Functional",
          label: "OOP",
          value: "1",
        },
        {
          id: "Design Patterns",
          parent: "OOP-Fun",
          label: "Design Patterns/SOLID/4 Pillars",
          value: "1",
        },
        {
          id: "APIs-Fun",
          parent: "Functional",
          label: "APIs",
          value: "1",
        },
        {
          id: "GraphQL",
          parent: "APIs-Fun",
          label: "GraphQL",
          value: "1",
        },
        {
          id: "Architecture",
          parent: "APIs-Fun",
          label: "SOA & Monolith Architecture",
          value: "1",
        },
        {
          id: "Web-Fun",
          parent: "Functional",
          label: "Web",
          value: "1",
        },
        {
          id: "JS",
          parent: "Web-Fun",
          label: "JavaScript",
          value: "1",
        },
        {
          id: "Frameworks",
          parent: "Web-Fun",
          label: "Web Framework in new language",
          value: "1",
        },
        {
          id: "Git-Fun",
          parent: "Functional",
          label: "Git",
          value: "1",
        },
        {
          id: "Rebase",
          parent: "Git-Fun",
          label: "Rebase",
          value: "1",
        },
        {
          id: "Stash",
          parent: "Git-Fun",
          label: "Stash",
          value: "1",
        },
        {
          id: "Cherry Picking",
          parent: "Git-Fun",
          label: "Cherry Picking",
          value: "1",
        },
        {
          id: "Log",
          parent: "Git-Fun",
          label: "Log & Reflog",
          value: "1",
        },
        {
          id: "Blame",
          parent: "Git-Fun",
          label: "Blame",
          value: "1",
        },
        {
          id: "Amend",
          parent: "Git-Fun",
          label: "Amend",
          value: "1",
        },
        {
          id: "Optimization-Fun",
          parent: "Functional",
          label: "Optimization",
          value: "1",
        },
        {
          id: "Big O",
          parent: "Optimization-Fun",
          label: "Big O",
          value: "1",
        },
        {
          id: "Testing-Fun",
          parent: "Functional",
          label: "Testing",
          value: "1",
        },
        {
          id: "Other Framework",
          parent: "Testing-Fun",
          label: "Testing in new language framework",
          value: "1",
        },
        {
          id: "Database-Fun",
          parent: "Functional",
          label: "Database",
          value: "1",
        },
        {
          id: "ORM",
          parent: "Database-Fun",
          label: "Object Relational Mapper",
          value: "1",
        },
        {
          id: "Ops-Fun",
          parent: "Functional",
          label: "Ops",
          value: "1",
        },
        {
          id: "CI",
          parent: "Ops-Fun",
          label: "Continuous Integration",
          value: "1",
        },
        {
          id: "Public",
          parent: "Ops-Fun",
          label: "Understanding public folder",
          value: "1",
        },
        {
          id: "Asset Pipeline",
          parent: "Ops-Fun",
          label: "Asset Pipeline",
          value: "1",
        },
        {
          id: "Security-Fun",
          parent: "Functional",
          label: "Security",
          value: "1",
        },
        {
          id: "CSRF/CORS",
          parent: "Security-Fun",
          label: "CSRF/CORS",
          value: "1",
        },
        {
          id: "SQL Injection",
          parent: "Security-Fun",
          label: "SQL Injection",
          value: "1",
        },
        {
          id: "SSL",
          parent: "Security-Fun",
          label: "SSL-always",
          value: "1",
        },
        {
          id: "Encrypting",
          parent: "Security-Fun",
          label: "Encrypting & Hashing sensitive data",
          value: "1",
        },
        {
          id: "Familiar",
          parent: "Learning Goals",
          label: "Familiar",
          value: "1",
        },
        {
          id: "Web-Fam",
          parent: "Familiar",
          label: "Web",
          value: "1",
        },
        {
          id: "DNS",
          parent: "Web-Fam",
          label: "DNS",
          value: "1",
        },
        {
          id: "CDNs",
          parent: "Web-Fam",
          label: "CDNs",
          value: "1",
        },
        {
          id: "Optimization-Fam",
          parent: "Familiar",
          label: "Optimization",
          value: "1",
        },
        {
          id: "Background Workers",
          parent: "Optimization-Fam",
          label: "Background Workers",
          value: "1",
        },
        {
          id: "Database-Fam",
          parent: "Familiar",
          label: "Database",
          value: "1",
        },
        {
          id: "noSQL",
          parent: "Database-Fam",
          label: "noSQL Database",
          value: "1",
        },
        {
          id: "Ops-Fam",
          parent: "Familiar",
          label: "Ops",
          value: "1",
        },
        {
          id: "Docker",
          parent: "Ops-Fam",
          label: "Docker",
          value: "1",
        },
        {
          id: "Lambda",
          parent: "Ops-Fam",
          label: "AWS Lambda",
          value: "1",
        },
        {
          id: "S3",
          parent: "Ops-Fam",
          label: "AWS S3",
          value: "1",
        },
        {
          id: "EC2",
          parent: "Ops-Fam",
          label: "AWS EC2",
          value: "1",
        },
        {
          id: "CS-Fam",
          parent: "Familiar",
          label: "CS",
          value: "1",
        },
        {
          id: "Stack",
          parent: "CS-Fam",
          label: "Stack",
          value: "1",
        },
        {
          id: "Queue",
          parent: "CS-Fam",
          label: "Queue",
          value: "1",
        },
        {
          id: "Heap",
          parent: "CS-Fam",
          label: "Heap",
          value: "1",
        },
        {
          id: "Graphs",
          parent: "CS-Fam",
          label: "Graphs",
          value: "1",
        },
        {
          id: "Recursion",
          parent: "CS-Fam",
          label: "Recursion",
          value: "1",
        },
        {
          id: "Sorting Algorithms",
          parent: "CS-Fam",
          label: "Sorting Algorithms",
          value: "1",
        },
        {
          id: "Security-Fam",
          parent: "Familiar",
          label: "Security",
          value: "1",
        },
        {
          id: "Click-jacking",
          parent: "Security-Fam",
          label: "Click-jacking",
          value: "1",
        },
        {
          id: "XSS",
          parent: "Security-Fam",
          label: "Cross-Site Scripting",
          value: "1",
        },
      ],
    },
  }).render();
});
